# Generated by Django 2.1.5 on 2019-11-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardTable',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('paragraph', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='categoryTable',
            fields=[
                ('categoryID', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='cardtable',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.categoryTable'),
        ),
    ]
