# Generated by Django 2.1.5 on 2019-11-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtable',
            old_name='categoryId',
            new_name='categoryID',
        ),
    ]
