# Generated by Django 2.1.5 on 2019-11-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20191106_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttable',
            name='cardID',
        ),
        migrations.DeleteModel(
            name='textTable',
        ),
    ]
