# Generated by Django 2.1.5 on 2019-11-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20191106_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardTableNew',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('paragraph', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.categoryTable')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cardtable',
            options={},
        ),
    ]
