# Generated by Django 2.1.5 on 2019-11-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_auto_20191107_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_table_new',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('serialNO', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('paragraph', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.categoryTable')),
            ],
        ),
    ]
