# Generated by Django 2.1.5 on 2019-11-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_card_table_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtable',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='cardtablenew',
            name='categoryID',
        ),
        migrations.AlterField(
            model_name='card_table_new',
            name='serialNO',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='cardTable',
        ),
        migrations.DeleteModel(
            name='cardTableNew',
        ),
    ]
