# Generated by Django 2.1.5 on 2019-11-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_auto_20191108_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTable',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('serialNO', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=30)),
                ('paragraph', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.categoryTable')),
            ],
        ),
    ]
