# Generated by Django 2.1.5 on 2019-11-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_auto_20191109_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_table_new',
            name='categoryID',
        ),
        migrations.DeleteModel(
            name='card_table_new',
        ),
    ]
