# Generated by Django 2.1.5 on 2019-11-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_image_list_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image_list_table',
        ),
        migrations.DeleteModel(
            name='image_table',
        ),
    ]
