# Generated by Django 2.1.5 on 2019-11-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_image_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_table',
            name='cardID',
        ),
        migrations.DeleteModel(
            name='image_table',
        ),
    ]
