# Generated by Django 2.1.5 on 2019-11-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0018_auto_20191110_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_table',
            name='cardID',
        ),
        migrations.DeleteModel(
            name='image_table',
        ),
    ]
