# Generated by Django 2.1.5 on 2019-11-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0023_auto_20191115_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_table',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='code_table',
            name='cardID',
        ),
        migrations.RemoveField(
            model_name='image_table',
            name='cardID',
        ),
        migrations.RemoveField(
            model_name='recommendation_table',
            name='cardID',
        ),
        migrations.DeleteModel(
            name='card_table',
        ),
        migrations.DeleteModel(
            name='categoryTable',
        ),
        migrations.DeleteModel(
            name='code_table',
        ),
        migrations.DeleteModel(
            name='image_table',
        ),
        migrations.DeleteModel(
            name='recommendation_table',
        ),
    ]
