# Generated by Django 2.1.5 on 2019-11-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0026_the_all_new_images_from_googledrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_title', models.CharField(max_length=200)),
                ('reference_serial_NO', models.IntegerField(default=0)),
                ('reference_link', models.CharField(max_length=300)),
                ('card_info_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.CardsInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='card_info_ID',
        ),
        migrations.RemoveField(
            model_name='recommendations',
            name='card_info_ID',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
